add-global-variants = true
no-hooks = true
no-tests = true

[psql]
host = "localhost"
dbname = "summit"
user="summit"
pass="icantsee"
sslmode = "disable"
whitelist = ["moderation_config", "moderation_mutes", "moderation_bans", "moderation_cases"]