add-global-variants = true
no-hooks = true
no-tests = true

[psql]
host = "localhost"
dbname = "asbwig"
user="asbwig"
pass="icantsee"
sslmode = "disable"
whitelist = ["economy_config", "economy_users", "economy_user_inventories", "economy_cooldowns", "economy_shop", "economy_createitem"]